Add new lints for flutter 3.24.5, dart 3.5.4 and metrics 5.7.6
miquido/lint_quido pull request #26
Opened 2024-12-31 10:34 UTC by paulkastel

Happy New Year, I guess... 🎆

2024-12-31 10:35 UTC, paulkastel commented
@PiotrMitkowski I think, you should do a release manually, since there has been no update on pub dev for over a year for this package.

2025-01-18 08:41 UTC, PiotrMitkowski requested changes

2025-01-18 08:41 UTC, PiotrMitkowski commented on README.md
> +  lint_quido: 1.24.5
Let's keep the approach, where we use MINOR version component to match the Flutter version, and leaving PATCH for potential minor fixes to the package. In that case, it would be `1.24.0`

2025-01-18 08:42 UTC, PiotrMitkowski commented
@paulkastel will do the manual release after merging this PR.

I've also seen some changes to the Dart GitHub Actions, so maybe we'll be able to FINALLY set the automated publish.

2025-01-18 08:51 UTC, paulkastel commented on README.md
> +  lint_quido: 1.24.5
Thanks, changed to bluesky... I mean 1.24.0

2025-01-22 16:07 UTC, PiotrMitkowski approved these changes
LGMT 🥐

2025-01-22 22:49 UTC, merged